services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: driver_db
      POSTGRES_USER: driver_user
      POSTGRES_PASSWORD: gwenchanA992#
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"